// <auto-generated />
namespace WebTasks.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class assigned_users : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(assigned_users));
        
        string IMigrationMetadata.Id
        {
            get { return "201704221937562_assigned_users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
